name: aur-auto-update

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get latest release
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const res = await github.rest.repos.getLatestRelease({
              owner: 'DataflareApp',
              repo: 'Dataflare'
            });
            const fs = require('fs');
            fs.appendFileSync(process.env.GITHUB_OUTPUT, `tag=${res.data.tag_name}\n`);
            fs.appendFileSync(process.env.GITHUB_OUTPUT, `version=${res.data.tag_name.replace(/^v/, '')}\n`);
      - name: Check if update is needed
        id: check_update
        run: |
          PKGVER=$(grep pkgver PKGBUILD | head -n1 | cut -d'=' -f2 | tr -d ' ')
          echo "Current pkgver: $PKGVER"
          echo "Latest version: ${{ steps.get_release.outputs.version }}"
          if [ "$PKGVER" = "${{ steps.get_release.outputs.version }}" ]; then
            echo "No update needed."
            echo "update_needed=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "update_needed=true" >> $GITHUB_OUTPUT
      - name: Download AppImages and calculate sha256sums
        if: steps.check_update.outputs.update_needed == 'true'
        run: |
          VERSION=${{ steps.get_release.outputs.version }}
          wget -O Dataflare-x86_64.AppImage https://assets.dataflare.app/release/linux/x86_64/Dataflare.AppImage
          wget -O Dataflare-aarch64.AppImage https://assets.dataflare.app/release/linux/aarch64/Dataflare.AppImage
          SHA_X86_64=$(sha256sum Dataflare-x86_64.AppImage | awk '{print $1}')
          SHA_AARCH64=$(sha256sum Dataflare-aarch64.AppImage | awk '{print $1}')
          echo "SHA_X86_64=$SHA_X86_64" >> $GITHUB_ENV
          echo "SHA_AARCH64=$SHA_AARCH64" >> $GITHUB_ENV
      - name: Update PKGBUILD and .SRCINFO
        if: steps.check_update.outputs.update_needed == 'true'
        run: |
          VERSION=${{ steps.get_release.outputs.version }}
          sed -i "s/^pkgver=.*/pkgver=$VERSION/" PKGBUILD
          sed -i "s/^pkgver =.*/pkgver = $VERSION/" .SRCINFO
          sed -i "s/^sha256sums_x86_64=.*/sha256sums_x86_64=('$SHA_X86_64')/" PKGBUILD
          sed -i "s/^sha256sums_x86_64 =.*/sha256sums_x86_64 = $SHA_X86_64/" .SRCINFO
          sed -i "s/^sha256sums_aarch64=.*/sha256sums_aarch64=('$SHA_AARCH64')/" PKGBUILD
          sed -i "s/^sha256sums_aarch64 =.*/sha256sums_aarch64 = $SHA_AARCH64/" .SRCINFO
      - name: Commit and push to AUR
        if: steps.check_update.outputs.update_needed == 'true'
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
      - name: Add AUR host key
        if: steps.check_update.outputs.update_needed == 'true'
        run: |
          mkdir -p ~/.ssh
          echo "aur.archlinux.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEuBKrPzbawxA/k2g6NcyV5jmqwJ2s+zpgZGZ7tpLIcN" >> ~/.ssh/known_hosts
          echo "aur.archlinux.org ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDKF9vAFWdgm9Bi8uc+tYRBmXASBb5cB5iZsB7LOWWFeBrLp3r14w0/9S2vozjgqY5sJLDPONWoTTaVTbhe3vwO8CBKZTEt1AcWxuXNlRnk9FliR1/eNB9uz/7y1R0+c1Md+P98AJJSJWKN12nqIDIhjl2S1vOUvm7FNY43fU2knIhEbHybhwWeg+0wxpKwcAd/JeL5i92Uv03MYftOToUijd1pqyVFdJvQFhqD4v3M157jxS5FTOBrccAEjT+zYmFyD8WvKUa9vUclRddNllmBJdy4NyLB8SvVZULUPrP3QOlmzemeKracTlVOUG1wsDbxknF1BwSCU7CmU6UFP90kpWIyz66bP0bl67QAvlIc52Yix7pKJPbw85+zykvnfl2mdROsaT8p8R9nwCdFsBc9IiD0NhPEHcyHRwB8fokXTajk2QnGhL+zP5KnkmXnyQYOCUYo3EKMXIlVOVbPDgRYYT/XqvBuzq5S9rrU70KoI/S5lDnFfx/+lPLdtcnnEPk=" >> ~/.ssh/known_hosts
          echo "aur.archlinux.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLMiLrP8pVi5BFX2i3vepSUnpedeiewE5XptnUnau+ZoeUOPkpoCgZZuYfpaIQfhhJJI5qgnjJmr4hyJbe/zxow=" >> ~/.ssh/known_hosts
      - name: Set up Git
        if: steps.check_update.outputs.update_needed == 'true'
        run: |
          git config --global user.email "aur@dataflare.app"
          git config --global user.name "dataflare-bot"
      - name: Push to AUR
        if: steps.check_update.outputs.update_needed == 'true'
        run: |
          git add PKGBUILD .SRCINFO LICENSE
          git commit -m "chore: update to ${{ steps.get_release.outputs.version }}"
          git remote add aur ssh://aur@aur.archlinux.org/dataflare-appimage.git
          git push aur master
